import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: { trackingId: string } }
) {
  try {
    const trackingId = params.trackingId
    
    // Simulate different states based on tracking ID
    if (trackingId.startsWith('test_')) {
      // For test tracking IDs, simulate a quick completion
      const elapsed = Date.now() - parseInt(trackingId.split('_')[1])
      
      if (elapsed < 10000) { // First 10 seconds - processing
        return NextResponse.json({
          success: true,
          trackingId,
          status: 'processing',
          processingTime: elapsed
        })
      } else { // After 10 seconds - completed
        return NextResponse.json({
          success: true,
          trackingId,
          status: 'completed',
          result: {
            success: true,
            timestamp: new Date().toISOString(),
            input: {
              keyword: "Test Keyword",
              location: "Test Location"
            },
            content: {
              html: "<h1>Test Article</h1><p>This is a test article generated by the polling mechanism.</p>",
              wordCount: 150,
              keywordDensity: "2.5%"
            },
            seo: {
              metaTitle: "Test Article - SEO Optimized",
              metaDescription: "This is a test meta description for the generated article.",
              focusKeywords: ["test keyword", "seo"],
              socialDescription: "Test social description"
            },
            contentStrategy: {
              searchIntent: "informational",
              targetLength: 1500,
              uniqueAngles: ["test angle 1", "test angle 2"]
            },
            validation: {
              targetKeyword: "test keyword",
              keywordMatches: 3,
              keywordDensity: "2.5%",
              validationApplied: true
            }
          },
          processingTime: elapsed
        })
      }
    }
    
    return NextResponse.json({
      success: false,
      error: 'Test tracking ID not found'
    }, { status: 404 })
    
  } catch (error) {
    console.error('Test status error:', error)
    return NextResponse.json(
      { 
        success: false, 
        error: 'Test status error' 
      },
      { status: 500 }
    )
  }
}
